#!/usr/bin/sh
VERSION="#TAG# - #TAG_DATE#"

# shellcheck disable=SC1091
. /usr/share/terminate-notice/helpers

start_action "$(basename "$0")-$VERSION"

eval "$(load_config announce)"

if [ "$VERIFY" = "1" ]
then
    echo "Action $(basename "$0")-$VERSION - INFO: Verified at start."
    exit 0
fi

# shellcheck disable=SC2154
if [ "$(first_of "$ANNOUNCE" "$announce" "1")" = "1" ]
then
    info announce Terminate Notice received.
fi